### ISSUE TITLE
Exception in the web crawler

### ISSUE THREAD

**Issue by zhangz22** [zhangz22/DeadlineCountdown#6]
The web crawler is reporting a bug:
Exception in thread "main" org.openqa.selenium.WebDriverException: Exception in thread "main" org.openqa.selenium.WebDriverException: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
Build info: version: '2.7.0', revision: '13926', time: '2011-09-23 15:09:51'
System info: os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:353)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:334)

Version and platform information are stated in the exception message

**Comment by zhangz22** [comment]
It seemed this problem is caused by Java itself.

**Comment by zhangz22** [comment]
> Issue resolved.!!! Below are the solutions.
>
> For Java 6: Add below jars into {JAVA_HOME}/jre/lib/ext. 1. bcprov-ext-jdk15on-154.jar 2. bcprov-jdk15on-154.jar
> 
> Add property into {JAVA_HOME}/jre/lib/security/java.security security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider
> 
> Java 7:download jar from below link and add to {JAVA_HOME}/jre/lib/security http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html
> 
> Java 8:download jar from below link and add to {JAVA_HOME}/jre/lib/security http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
> 
> Issue is that it is failed to decrypt 256 bits of encryption.

[Ref](https://stackoverflow.com/questions/38203971/javax-net-ssl-sslhandshakeexception-received-fatal-alert-handshake-failure)
